"use client";
import { FormEvent, useCallback, useEffect, useState } from "react";

type Cohort={id:number;name:string;cancerType:string;status:string;createdAt:string};
type Patient={id:number;patientCode:string;age:number;sex:string;cancerType:string;stage:string;biomarker:string;status:string;site:string;consentStatus:string};
type Audit={id:number;detail:string;actorEmail:string;createdAt:string};

export function CohortManager(){
  const [tab,setTab]=useState<"cohorts"|"patients"|"activity">("cohorts"); const [cohorts,setCohorts]=useState<Cohort[]>([]); const [patients,setPatients]=useState<Patient[]>([]); const [events,setEvents]=useState<Audit[]>([]); const [message,setMessage]=useState(""); const [busy,setBusy]=useState(false);
  const load=useCallback(async()=>{const [c,p,a]=await Promise.all([fetch("/api/cohorts"),fetch("/api/patients"),fetch("/api/activity")]);if(c.ok)setCohorts((await c.json()).cohorts);if(p.ok)setPatients((await p.json()).patients);if(a.ok)setEvents((await a.json()).events)},[]);
  useEffect(()=>{void load()},[load]);
  async function submitCohort(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);const data=new FormData(e.currentTarget);const res=await fetch("/api/cohorts",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({name:data.get("name"),cancerType:data.get("cancerType")})});setMessage(res.ok?"Cohort saved.":"Please check the cohort details.");if(res.ok){e.currentTarget.reset();await load()}setBusy(false)}
  async function submitPatient(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);const data=Object.fromEntries(new FormData(e.currentTarget));const res=await fetch("/api/patients",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(data)});setMessage(res.ok?"Demonstration patient added.":((await res.json()).error??"Could not add patient."));if(res.ok){e.currentTarget.reset();await load()}setBusy(false)}
  async function remove(id:number){if(!confirm("Delete this cohort?"))return;await fetch(`/api/cohorts?id=${id}`,{method:"DELETE"});await load()}
  async function enroll(patientId:number,cohortId:number){if(!cohortId)return;const res=await fetch("/api/enrollments",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({patientId,cohortId})});setMessage(res.ok?"Patient enrolled.":((await res.json()).error??"Enrollment failed."));if(res.ok)await load()}
  return <section className="manager panel" id="cohort-manager"><div className="managerHead"><div><p className="managerKicker">CLINICAL WORKFLOWS</p><h2>Manage your research records</h2><p>Saved securely to your private workspace. Use demonstration identifiers only.</p></div><span className="demoBadge">DEMO DATA</span></div><div className="managerTabs" role="tablist"><button className={tab==="cohorts"?"active":""} onClick={()=>setTab("cohorts")}>Cohorts <span>{cohorts.length}</span></button><button className={tab==="patients"?"active":""} onClick={()=>setTab("patients")}>Patients <span>{patients.length}</span></button><button className={tab==="activity"?"active":""} onClick={()=>setTab("activity")}>Audit trail <span>{events.length}</span></button></div>{message&&<div className="managerMessage" role="status">{message}<button onClick={()=>setMessage("")}>×</button></div>}
  {tab==="cohorts"&&<div className="managerBody"><form className="recordForm" onSubmit={submitCohort}><h3>Create a cohort</h3><label>Cohort name<input required maxLength={100} name="name" placeholder="e.g. Early-stage breast cancer"/></label><label>Cancer type<select required name="cancerType" defaultValue=""><option value="" disabled>Select type</option>{["Breast","Prostate","Lung","Ovarian","Colorectal","Other"].map(x=><option key={x}>{x}</option>)}</select></label><button disabled={busy}>{busy?"Saving…":"Create cohort"}</button></form><div className="records"><h3>Saved cohorts</h3>{cohorts.length?cohorts.map(c=><article key={c.id}><div><b>{c.name}</b><span>{c.cancerType} · {c.status}</span></div><button onClick={()=>remove(c.id)} aria-label={`Delete ${c.name}`}>Delete</button></article>):<Empty text="No saved cohorts yet. Create your first cohort."/>}</div></div>}
  {tab==="patients"&&<div className="patientManager"><form className="patientForm" onSubmit={submitPatient}><label>Patient code<input required name="patientCode" maxLength={30} placeholder="DEMO-001"/></label><label>Age<input required name="age" type="number" min="0" max="120"/></label><label>Sex<select required name="sex" defaultValue=""><option value="" disabled>Select</option><option value="F">Female</option><option value="M">Male</option><option>Other</option></select></label><label>Cancer type<input required name="cancerType"/></label><label>Stage<select required name="stage" defaultValue=""><option value="" disabled>Select</option>{["I","II","III","IV","Not staged"].map(x=><option key={x}>{x}</option>)}</select></label><label>Biomarker<input name="biomarker" placeholder="Not recorded"/></label><label>Site<input required name="site"/></label><label>Consent<select required name="consentStatus" defaultValue="Pending"><option>Pending</option><option>Documented</option><option>Declined</option></select></label><button disabled={busy}>{busy?"Saving…":"Add demonstration patient"}</button></form><div className="managedTable"><table><thead><tr><th>Patient</th><th>Diagnosis</th><th>Consent</th><th>Enroll in</th></tr></thead><tbody>{patients.map(p=><tr key={p.id}><td><b>{p.patientCode}</b><small>{p.age} / {p.sex} · {p.site}</small></td><td>{p.cancerType} · Stage {p.stage}<small>{p.biomarker}</small></td><td><span className={`consent ${p.consentStatus.toLowerCase()}`}>{p.consentStatus}</span></td><td><select aria-label={`Enroll ${p.patientCode}`} defaultValue="" onChange={e=>{void enroll(p.id,Number(e.target.value));e.target.value=""}}><option value="">Choose cohort</option>{cohorts.map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select></td></tr>)}</tbody></table>{!patients.length&&<Empty text="No demonstration patients saved yet."/>}</div></div>}
  {tab==="activity"&&<div className="auditList">{events.length?events.map(e=><article key={e.id}><i>✓</i><div><b>{e.detail}</b><span>{e.actorEmail} · {new Date(e.createdAt).toLocaleString()}</span></div></article>):<Empty text="Audit activity will appear here."/>}</div>}</section>
}
function Empty({text}:{text:string}){return <div className="managerEmpty"><b>Nothing here yet</b><span>{text}</span></div>}
