"use client";
import {FormEvent, useEffect, useState} from "react";
import {WorkspaceHeader} from "../workspace-header";
import "./settings.css";
import "./logout.css";
type Settings={workspace:string;organization:string;timezone:string;dateFormat:string;emailDigest:boolean;eligibilityAlerts:boolean;exportApproval:boolean;sessionTimeout:string};
const defaults:Settings={workspace:"Oncology Research Workspace",organization:"West African Oncology Collaborative",timezone:"Africa/Lagos",dateFormat:"DD/MM/YYYY",emailDigest:true,eligibilityAlerts:true,exportApproval:true,sessionTimeout:"30 minutes"};
export default function SettingsPage(){
  const [settings,setSettings]=useState(defaults);const [saved,setSaved]=useState(false);
  useEffect(()=>{try{const stored=localStorage.getItem("oncocohort-admin-settings");if(stored)setSettings({...defaults,...JSON.parse(stored)})}catch{/* Ignore malformed device-local preferences and keep safe defaults. */}},[]);
  function update<K extends keyof Settings>(key:K,value:Settings[K]){setSettings(current=>({...current,[key]:value}));setSaved(false)}
  function submit(event:FormEvent){event.preventDefault();localStorage.setItem("oncocohort-admin-settings",JSON.stringify(settings));setSaved(true);window.setTimeout(()=>setSaved(false),3000)}
  function reset(){setSettings(defaults);localStorage.removeItem("oncocohort-admin-settings");setSaved(false)}
  return <main><WorkspaceHeader active="settings"/><div className="settingsPage">
    {saved&&<div className="toast" role="status">Settings saved successfully</div>}
    <section className="settingsIntro"><div><p>ADMINISTRATION</p><h1>Workspace settings</h1><span>Manage workspace identity, regional defaults, notifications, and data governance.</span></div><span className="adminBadge">ADMIN ACCESS</span></section>
    <form onSubmit={submit}><div className="settingsLayout"><aside className="panel settingsNav"><b>Settings</b><a href="#general">General</a><a href="#notifications">Notifications</a><a href="#governance">Data governance</a><a href="#access">Access & roles</a></aside><div className="settingsContent">
      <section className="panel settingsCard" id="general"><header><div><h2>General</h2><p>Workspace identity and regional preferences.</p></div><i>01</i></header><div className="settingsFields"><label>Workspace name<input value={settings.workspace} onChange={e=>update("workspace",e.target.value)} required maxLength={80}/></label><label>Organization<input value={settings.organization} onChange={e=>update("organization",e.target.value)} required maxLength={100}/></label><label>Timezone<select value={settings.timezone} onChange={e=>update("timezone",e.target.value)}><option>Africa/Lagos</option><option>Africa/Accra</option><option>Africa/Nairobi</option><option>UTC</option></select></label><label>Date format<select value={settings.dateFormat} onChange={e=>update("dateFormat",e.target.value)}><option>DD/MM/YYYY</option><option>MM/DD/YYYY</option><option>YYYY-MM-DD</option></select></label></div></section>
      <section className="panel settingsCard" id="notifications"><header><div><h2>Notifications</h2><p>Choose which operational updates administrators receive.</p></div><i>02</i></header><Toggle title="Weekly activity digest" copy="Receive a summary of cohort and patient changes every Monday." checked={settings.emailDigest} onChange={v=>update("emailDigest",v)}/><Toggle title="Eligibility alerts" copy="Notify administrators when records need eligibility review." checked={settings.eligibilityAlerts} onChange={v=>update("eligibilityAlerts",v)}/></section>
      <section className="panel settingsCard" id="governance"><header><div><h2>Data governance</h2><p>Controls that help protect demonstration and clinical workspace data.</p></div><i>03</i></header><Toggle title="Require approval for exports" copy="An administrator must approve patient directory exports." checked={settings.exportApproval} onChange={v=>update("exportApproval",v)}/><div className="settingRow"><div><b>Inactive session timeout</b><span>Automatically end inactive administrator sessions.</span></div><select value={settings.sessionTimeout} onChange={e=>update("sessionTimeout",e.target.value)}><option>15 minutes</option><option>30 minutes</option><option>1 hour</option><option>4 hours</option></select></div><div className="governanceNote"><b>Audit logging is always enabled</b><span>Administrative and record-level changes remain available in Workspace Activity.</span><a href="/activity">View activity →</a></div></section>
      <section className="panel settingsCard" id="access"><header><div><h2>Access & roles</h2><p>Current workspace administrators and role permissions.</p></div><i>04</i></header><div className="adminUser"><span>SA</span><div><b>Dr. S. Adeyemi</b><small>Workspace owner · Full administrative access</small></div><em>OWNER</em><a className="logoutButton" href="/logout">Log out</a></div><p className="accessNote">Logging out securely ends the current identity session. Additional member invitations will be available after organizational governance review.</p></section>
    </div></div><footer className="settingsActions"><button type="button" onClick={reset}>Restore defaults</button><button type="submit">Save settings</button></footer></form>
  </div></main>
}
function Toggle({title,copy,checked,onChange}:{title:string;copy:string;checked:boolean;onChange:(value:boolean)=>void}){return <label className="settingRow toggleRow"><div><b>{title}</b><span>{copy}</span></div><input aria-label={title} type="checkbox" checked={checked} onChange={e=>onChange(e.target.checked)}/><i aria-hidden="true"/></label>}
